### ISSUE TITLE
Javascript Logic ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by Axxiar** [Niilyx/sudoku-nsi#4]
# Miam miam, javascript à des règles très bizarres et on adore ça ! 

####  Voilà quelques erreurs que j'ai trouvé et qui sont pas faciles à dénicher étant donné le fonctionnement de js
- @Niilyx je penses qu'il faut test la `length` des tableau. Mais visiblement ça marche de tester des trucs du style `[0,1] > 1` sauf je sais pas ce que ça fait.
https://github.com/Niilyx/sudoku-nsi/blob/7b14cb0677b2ba74f2d241f89fb65de083c908a5/js/sudoku.js#L143

- et ici, il semblerait que pour `for  (i in [...])` , `i` prend les valeurs `0,1,2,...` mais ce sont des strings (nani?). 
https://github.com/Niilyx/sudoku-nsi/blob/7b14cb0677b2ba74f2d241f89fb65de083c908a5/js/sudoku.js#L140
ça fait des trucs bizarre du style, juste après `get_column(j+1)` ça va faire `get_column(11)` parce qu'en js `"1"+1` ça donne `11`

**Comment by Axxiar** [comment]
oh cool on peut assigner des gens

**Comment by Niilyx** [comment]
quelle horreur....

*JS\*

🤮
