### ISSUE TITLE
Alors peut être

### ISSUE THREAD

**Issue by Axxiar** [Niilyx/sudoku-nsi#5]
Okay je crois bien que c'est bon cette fois 

Par contre c'est un peu bizarre parce que la fonction qui vérifie si le sudoku est valide renvoie `False` alors qu'en testant avec les fonctions d'autres personnes, ça semble être bon à chaque fois 
cf. [ce fichier](https://github.com/Niilyx/sudoku-nsi/blob/axxiar-tests/python/tests.py)

la fonction bizarre : https://github.com/Niilyx/sudoku-nsi/blob/f09e1979c64aecf0f276546ffc1d7308bc4d104f/python/solution.py#L193

Donc faudrait vérifier si y'a pas un soucis avec la [fonction](https://github.com/Niilyx/sudoku-nsi/blob/f09e1979c64aecf0f276546ffc1d7308bc4d104f/python/solution.py#L193), et si les sudokus sont biens valides

**Comment by Niilyx** [comment]
get_square fixé (le responsable de ce pb)
